-- 코드를 작성해주세요
select a.ITEM_ID, a.ITEM_NAME, a.RARITY
from ITEM_INFO a
join ITEM_TREE b on a.ITEM_ID = b.ITEM_ID
JOIN
    ITEM_INFO c ON b.PARENT_ITEM_ID = c.ITEM_ID
WHERE
    a.RARITY = 'RARE'
ORDER BY
    b.ITEM_ID DESC